# Generated by Django 2.0.5 on 2018-05-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180516_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookcover',
            field=models.ImageField(blank=True, help_text='Upload bookcover', null=True, upload_to=''),
        ),
    ]
